[package]
name = "rust-manychain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
sha2 = "0.11.0-pre.4"
data-encoding = "2.6.0"
bincode = "2.0.0-rc.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
